### ISSUE TITLE
MAGEIO FFMPEG_WRITER WARNING

### ISSUE THREAD

**Issue by DennisFaucher** [zishor/yolo-python-rtsp#4]
Environment
* python3
* Ubuntu 18.04 x86_64

TIA

python3 yolo_opencv.py --input sampledata/commuters.mp4 --config cfg/yolov3-tiny.cfg --weights yolov3-tiny.weights --classes cfg/yolov3.txt

IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (1920, 1080) to (1920, 1088) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).
Detecting objects in frame 1
Traceback (most recent call last):
  File "yolo_opencv.py", line 188, in <module>
    processvideo(os.path.join(args.input))
  File "yolo_opencv.py", line 140, in processvideo
    image = detect(frame)
  File "yolo_opencv.py", line 81, in detect
    net = cv2.dnn.readNet(args.weights, args.config)
cv2.error: OpenCV(4.2.0) /io/opencv/modules/dnn/src/darknet/darknet_importer.cpp:214: error: (-212:Parsing error) Failed to parse NetParameter file: yolov3-tiny.weights in function 'readNetFromDarknet'

No frames have been written; the written video is invalid.
Finishing stream 0:0 without any data written to it.

**Comment by nigharsh** [comment]
Problem is with yolov3-tiny.weights file. Please check the filename/location.

**Comment by DennisFaucher** [comment]
Thank you

**Comment by foschmitz** [comment]
Closing — this was caused by a missing/wrong weights file path. PR #10 now validates that weights and config files exist before running and shows a clear error message with download instructions.
