### ISSUE TITLE
IndexError: invalid index to scalar variable.

### ISSUE THREAD

**Issue by maniack** [zishor/yolo-python-rtsp#7]
https://github.com/foschmitz/yolo-python-rtsp/blob/9c94a01e108c10301b5e360691dc8feaf79dcf88/yolo_opencv.py#L50

```
Detecting objects in frame 0
Traceback (most recent call last):
  File "yolo_opencv.py", line 172, in <module>
    frame = detect(frame)
  File "yolo_opencv.py", line 87, in detect
    outs = net.forward(get_output_layers(net))
  File "yolo_opencv.py", line 50, in get_output_layers
    output_layers = [layer_names[i[0] - 1] for i in net.getUnconnectedOutLayers()]
  File "yolo_opencv.py", line 50, in <listcomp>
    output_layers = [layer_names[i[0] - 1] for i in net.getUnconnectedOutLayers()]
IndexError: invalid index to scalar variable.
```

Hello!

I'm not a Python guru, but stackoverflow says that we ned to change `i[0] - 1` to `i - 1` to fix this error ¯\\\_(ツ)\_/¯
Sorry if I'm wrong...

**Comment by stingwraith** [comment]
Stackoverflow was correct. In yolo_opencv.py, just change both instances of "i[0]" to just "i" (without quotes) and it should run fine!

**Comment by taivnn9** [comment]
You can try 2 solutions
- Change `layer_names[i[0] - 1] to layer_names[i - 1]` https://stackoverflow.com/a/72669466/12461080
- Change  OpenCV  version > 4.5.3 https://stackoverflow.com/a/69771479/12461080

Change OpenCV works fine with me.
