### ISSUE TITLE
Error With Fresh Install 

### ISSUE THREAD

**Issue by stingwraith** [zishor/yolo-python-rtsp#9]
Command run: 
python3 yolo_opencv.py --input sampledata/commuters.mp4 --config cfg/yolov3-tiny.cfg --weights yolov3-tiny.weights --classes cfg/yolov3.txt

Error:
IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (1920, 1080) to (1920, 1088) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).
Detecting objects in frame 1
Traceback (most recent call last):
  File "yolo_opencv.py", line 188, in <module>
    processvideo(os.path.join(args.input))
  File "yolo_opencv.py", line 140, in processvideo
    image = detect(frame)
  File "yolo_opencv.py", line 87, in detect
    outs = net.forward(get_output_layers(net))
  File "yolo_opencv.py", line 50, in get_output_layers
    output_layers = [layer_names[i[0] - 1] for i in net.getUnconnectedOutLayers()]
  File "yolo_opencv.py", line 50, in <listcomp>
    output_layers = [layer_names[i[0] - 1] for i in net.getUnconnectedOutLayers()]
IndexError: invalid index to scalar variable.
No frames have been written; the written video is invalid.

Any help would be greatly appreciated!

**Comment by stingwraith** [comment]
I was able to fix this issue by changing all instances of "i[0]" to just "i"
